services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ${PROJECTS_PATH:-./projects}:/var/www/html:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-available:/etc/nginx/sites-available:rw
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./docker/nginx/logs:/var/log/nginx:rw
    depends_on:
      - php
    networks:
      - laravel_network
    restart: unless-stopped

  file-watcher:
    build: 
      context: ./docker/file-watcher
      dockerfile: Dockerfile
    container_name: file_watcher
    volumes:
      - ${PROJECTS_PATH:-./projects}:/var/www/html:rw
      - ./docker/nginx/sites-available:/etc/nginx/sites-available:rw
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PROJECTS_PATH=/var/www/html
      - DOMAIN_SUFFIX=${DOMAIN_SUFFIX:-.test}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    depends_on:
      - nginx
    networks:
      - laravel_network
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_fpm
    volumes:
      - ${PROJECTS_PATH:-./projects}:/var/www/html:rw
    working_dir: /var/www/html
    networks:
      - laravel_network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 2G
      MAX_EXECUTION_TIME: 600
    volumes:
      - ./docker/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
    ports:
      - "8182:80"
    depends_on:
      - mysql
    networks:
      - laravel_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
